// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghagchreunwgaahsoecp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoYWdjaHJldW53Z2FhaHNvZWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzY4MDYsImV4cCI6MjA2NTc1MjgwNn0.tymYrEoiVLVGxE8Wi9_CMEFU-cAKH_CX4JvF-U2_5IE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);